server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 9998

websocketClientConfiguration:
  serverHost: ws://localhost:8036
  clientHost: http://localhost:9998
  threadPoolSize: 5 # 5 threads
  initialDelay: 30 # 0 seconds delay on startup
  period: 30 #seconds